version: "3.8"
services:
  web:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: .docker/Dockerfile
    container_name: "web"
    ports:
      - "8080:3000"
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpwd'
      MYSQL_ROOT_PASSWORD: 'rootpwd'
    container_name: "db"
    ports:
      - "8989:3306"
    volumes:
      - "./.docker/data/db/mysql:/var/lib/mysql"
